on:
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with: 
        java-version: 1.8
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
    - name: Build with Maven
      run: mvn clean package
          
    - uses: actions/upload-artifact@v1
      with:
        name: verademo.war
        path: target/verademo.war
        

  pipeline_scan:
      needs: build
      runs-on: ubuntu-latest
      name: pipeline scan

      steps:
        - name: checkout repo
          uses: actions/checkout@v2
          
        - name: get archive
          uses: actions/download-artifact@v2
          with:
            name: verademo.war
          
        - name: show folder
          run: |
            env

        - name: pipeline-scan action step
          id: pipelien-scan
          uses: wasptree/Veracode-pipeline-scan-action@beta-0.1a
          with:
            vid: ${{ secrets.VID }}
            vkey: ${{ secrets.VKEY }}
            file: "verademo.war" 
            request_policy: "VeraDemo Policy"
            store_baseline_file: true
            store_baseline_file_branch: "feature-123"
            create_baseline_from: "standard"
            debug: 1
            fail_build: true
            
